app:
  cards-on-page: 2
  max-messages-in-chat: 20

server:
  port: 8080

spring:
  application:
    name: gate
  jpa:
    open-in-view: true
  profiles:
    default: h2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
