spring:
  datasource:
    url: jdbc:h2:mem:social-network
    driverClassName: "org.h2.Driver"
    username: h2
    password: pass
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true